### PR TITLE
Tests for all array and list property types

### PR DESCRIPTION
**Pull request by c42f**
Also implement length(::Ply) to be consistent with the iterator
interface.

### CODE REVIEW

**Comment by andyferris** [comment]
Cool, looks good.

I'm curious - where would you use this and not want `getindex` with an integer?

**Comment by c42f** [comment]
`length` is rather overloaded - is it part of the `AbstractArray` interface, part of the iterator interface, part of the `Associative` interface, part of the general container interface, etc?  In this case, `Ply` is perhaps more like an `Associative` than an array, so `length()` + `getindex(::String)` makes some sense?

In this case, I wanted to check the number of elements in the `Ply` in the tests.

**Comment by c42f** [comment]
By the way, I'm not entirely sure the `Ply` API really knows what kind of containers things are... I guess `Ply` is mostly Associative-like, `Element` is Table-like, and Property is array-like.  The only ones of these which are formalized are `ArrayProperty` and `ListProperty` which are currently types of of `AbstractVector`.

**Comment by andyferris** [comment]
Yes that is interesting... a `Dict{String,DataFrame}` :)

I see length is defined on `Dict`s so +1 from me!

**Pull request merged**
